### PR TITLE
Save copies of log messages in /app/data/logs via syslog-sink container

### PR DESCRIPTION
**Pull request by philbudne**
See https://github.com/mediacloud/story-indexer/issues/120

### CODE REVIEW

**Comment by philbudne** [comment]
Example from log file messages.log:
```
2023-11-28 23:48:17,949 c1a736ca37df parser INFO: parsed http://lamdongtv.vn/tin-tuc-n9992/tap-trung-trien-khai-cac-du-an-trong-diem-giao-thong-quoc-gia.html with trafilatura date 2021-01-24
2023-11-28 23:48:17,954 c1a736ca37df parser INFO: processed #63 in 154.531 ms, status: ok
2023-11-28 23:48:17,954 c1a736ca37df parser INFO: _process_one_message #64
2023-11-28 23:48:17,955 c1a736ca37df parser INFO: ack and commit #63
2023-11-28 23:48:17,956 c1a736ca37df parser INFO: parsing http://lamdongtv.vn/tin-tuc-n16664/tap-trung-trien-khai-cac-du-an-trong-diem-giao-thong-quoc-gia.html: 61030 characters
2023-11-28 23:48:17,959 36a13d54c675 importer INFO: on_message tag #63
2023-11-28 23:48:17,960 36a13d54c675 importer INFO: _process_one_message #63
2023-11-28 23:48:17,966 36a13d54c675 importer INFO: HEAD http://elasticsearch1:9200/mediacloud_search_text_2021 [status:200 duration:0.005s]
2023-11-28 23:48:17,977 36a13d54c675 importer INFO: PUT http://elasticsearch1:9200/mediacloud_search_text_2021/_create/dc1b655d56c45a462fef62aae5577f85f2448a2e38855572fe438ce01e1543ee [status:201 duration:0.010s]
2023-11-28 23:48:17,977 36a13d54c675 importer INFO: Story has been successfully imported. to index mediacloud_search_text_2021
2023-11-28 23:48:17,980 36a13d54c675 importer INFO: processed #63 in 19.626 ms, status: ok
2023-11-28 23:48:17,981 36a13d54c675 importer INFO: ack and commit #63
2023-11-28 23:48:17,984 21e46d97f1e8 archiver INFO: on_message tag #63
2023-11-28 23:48:17,985 21e46d97f1e8 archiver INFO: _process_one_message #63
2023-11-28 23:48:17,993 21e46d97f1e8 archiver INFO: processed #63 in 6.834 ms, status: ok
2023-11-28 23:48:17,993 21e46d97f1e8 archiver INFO: waiting 821.563 seconds for batch message 64
2023-11-28 23:48:18,098 c1a736ca37df parser INFO: parsed http://lamdongtv.vn/tin-tuc-n16664/tap-trung-trien-khai-cac-du-an-trong-diem-giao-thong-quoc-gia.html with trafilatura date 2022-10-20
2023-11-28 23:48:18,104 c1a736ca37df parser INFO: processed #64 in 147.585 ms, status: ok
2023-11-28 23:48:18,105 c1a736ca37df parser INFO: ack and commit #64
2023-11-28 23:48:18,108 36a13d54c675 importer INFO: on_message tag #64
2023-11-28 23:48:18,109 36a13d54c675 importer INFO: _process_one_message #64
2023-11-28 23:48:18,124 36a13d54c675 importer INFO: HEAD http://elasticsearch1:9200/mediacloud_search_text_2022 [status:200 duration:0.014s]
2023-11-28 23:48:18,136 36a13d54c675 importer INFO: PUT http://elasticsearch1:9200/mediacloud_search_text_2022/_create/34fdf9489eea722c537bef56afd31dd69540c8a0773035ce9fdaa38b1aced23d [status:201 duration:0.011s]
2023-11-28 23:48:18,137 36a13d54c675 importer INFO: Story has been successfully imported. to index mediacloud_search_text_2022
2023-11-28 23:48:18,141 36a13d54c675 importer INFO: processed #64 in 30.583 ms, status: ok
2023-11-28 23:48:18,142 36a13d54c675 importer INFO: ack and commit #64
2023-11-28 23:48:18,145 21e46d97f1e8 archiver INFO: on_message tag #64
2023-11-28 23:48:18,146 21e46d97f1e8 archiver INFO: _process_one_message #64
2023-11-28 23:48:18,155 21e46d97f1e8 archiver INFO: processed #64 in 8.046 ms, status: ok
2023-11-28 23:48:18,155 21e46d97f1e8 archiver INFO: waiting 821.401 seconds for batch message 65
```

**Comment by philbudne** [comment]
Fetcher not logging correctly.  Converted to Draft

**Review by kilemensi — APPROVED** [review]
🚀 

-----

> It looks likee Docker CAN forward logs using syslog, but has to depend on the messages being in a specific format to parse/extract the priority: https://docs.docker.com/config/containers/logging/syslog/

Isn't it easier to change our message format to match what Docker expects so that we only need to change logging driver once per host and receive logs from every container automagically?

**Review by pgulley — APPROVED** [review]

**Comment by philbudne** [comment]
fixes https://github.com/mediacloud/story-indexer/issues/119

**Pull request merged**
