### PR TITLE
Remove news search api from deploy

### PR DESCRIPTION
**Pull request by thepsalmist**
This PR removes News Search API deployment configurations to decouple its deployment from story-indexer.

### CODE REVIEW

**Review by kilemensi — APPROVED** [review]

**Review by philbudne — APPROVED** [review]
Thanks for removing all of the associated variables from deploy.sh!!!

"Remove news search api from deploy" might be a clearer choice for the PR title; Words like "fix" and "cleanup" imply there was something broken or there was a mess, sentiments that aren't always the best introduction for your changes!

NOTE! This PR should not be merged/deployed until replacement production stack is up and running!!!

**Comment by thepsalmist** [comment]
> Thanks for removing all of the associated variables from deploy.sh!!!
> 
> "Remove news search api from deploy" might be a clearer choice for the PR title; Words like "fix" and "cleanup" imply there was something broken or there was a mess, sentiments that aren't always the best introduction for your changes!
> 
> NOTE! This PR should not be merged/deployed until replacement production stack is up and running!!!

Sure, once the replacement stack is ready will scale down the indexer news-search-api , then merge for new release?

**Comment by philbudne** [comment]
> Sure, once the replacement stack is ready will scale down the indexer news-search-api , then merge for new release?

Sounds good.

**Comment by philbudne** [comment]
I suspect the old services (news-search-api and -ui) will need to be
manually removed after the PR is merged and deployed.

**Comment by thepsalmist** [comment]
Old service in the indexer stack removed & switched to `nes-search-api` stack

**Pull request merged**
