### PR TITLE
chore: ES reindex implementation

### PR DESCRIPTION
**Pull request by thepsalmist**
This PR addresses Issue #340

### CODE REVIEW

**Comment by kilemensi** [comment]
My (very) quick thoughts:

1. Won't the script be better in Python (it could be just me and my `sh` allergies)?
2. How do we plan on using this script?
   i. Would we want to use it to `reindex` documents matching a certain query? In that case, the script should support a `query`,
   ii. Do we care about any impact running this script could have on the cluster?, Then the script should support `throttling` or `slicing`, etc.

**Comment by thepsalmist** [comment]
> My (very) quick thoughts:
> 
> 1. Won't the script be better in Python (it could be just me and my `sh` allergies)?
> 2. How do we plan on using this script?
>    i. Would we want to use it to `reindex` documents matching a certain query? In that case, the script should support a `query`,
>    ii. Do we care about any impact running this script could have on the cluster?, Then the script should support `throttling` or `slicing`, etc.

On the support for `throttling`, I'm not sure we wan't to define the `requests_per_second` to set throttling on initial `reindex` request without knowing the impact on the cluster. 
Since we've settled on Kibana being part of the cluster, I believe we can set this using the [Rethrottle API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-rethrottle) based on the monitoring stats

**Review by m453h — APPROVED** [review]
Looks good 🚀

**Review by pgulley — APPROVED** [review]
I trust the details here- thanks for including good documentation!

**Review by kilemensi — APPROVED** [review]
My bash-fu ain't all that but LGTM

**Pull request merged**
